# Generated by Django 4.2.5 on 2023-09-29 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
