# Generated by Django 4.2.5 on 2023-09-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='courses',
        ),
    ]
