# Generated by Django 4.2.5 on 2023-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_lesson_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.URLField(default='www.piton.org', max_length=150, verbose_name='Ссылка'),
        ),
    ]
